sudo: false
language: node_js
node_js:
  - 'node'

branches:
  only:
  - master
  - /v\d\./

services: mongodb

matrix:
  include:
  - env: SCRIPT=lint

cache:
  directories:
    - node_modules

script:
  - if [ "$SCRIPT" ]; then npm run $SCRIPT; fi

before_deploy:
  - if [ "$TRAVIS_TAG" ]; then npm run build:prod; fi
  - if [ -z "${TRAVIS_TAG+xxx}" ]; then npm run build:staging; fi
  - git config --global user.name "travis CI"
  - git config --global user.email "admin@travis-ci.org"
  - git add -f client-dist
  - git commit -m "add client-dist"

deploy:
  - provider: heroku
    app: trumpocalypse-io-test
    api_key:
      secure: JvZ9Jg4GZUhduCBm5UqOyY0HkpzxvUhlMHyPwx0FrcKtwx9BIlDPQzzb8hFKtv6xagWpULAIQjy/ZcdXHvb9W2ullGMjDSguJoYY67ZC8lb1Qofg12gDxLhSVVAKzqSngjINNhkm1Gls4kUGjBrYyAkPSbydDB5cnkHiygYAUQdLGtkbInXjtH/49Tyy8If8hLP4l5ymcqOPSnkWQ7kOs0CbZkdECts3lycMZ2yi86WoeYMVxgI690HbepnGO6VUtloNWB5p3/iEjMkAwzGPRI/6YJK2nSghfZj0ylMTlOO0NbRsEZs/Lmr5SQVy4fZS+OZP7qYfBxFQinCxplQx8MK8pDnrVM2p2m7XSk6jb7cAEmzbGBH5cUMAdy67en7acJOlAzGwj5dGO9POC0J74PMLSPocOxAjYq6wLvLPRvg/FcWzNdkw/2hXzI/KFAmBOCdNAyQqQeMtrMoZCPpN6DQDmOjdyPEMlksTlKXSsgbUmHMcsSdh5d3DtFnzla3WlHOZWR97lmA2y02B7SLGrLrXjqam1xJWG+J4lbLrXlCiYAOZnDYBTww/WlYQ3oP6drgqwxAYdUOlUomc20NkZJy3WujZUGlWAk5YMc10rF0HKcfy25HqnIcvP0lSUx1fw2Kqs9HVWNXreJRiokBbnVCgg1OfYbdovM8vXC/BRYQ=
  - provider: heroku
    app: trumpocalypse-io
    api_key:
      secure: JvZ9Jg4GZUhduCBm5UqOyY0HkpzxvUhlMHyPwx0FrcKtwx9BIlDPQzzb8hFKtv6xagWpULAIQjy/ZcdXHvb9W2ullGMjDSguJoYY67ZC8lb1Qofg12gDxLhSVVAKzqSngjINNhkm1Gls4kUGjBrYyAkPSbydDB5cnkHiygYAUQdLGtkbInXjtH/49Tyy8If8hLP4l5ymcqOPSnkWQ7kOs0CbZkdECts3lycMZ2yi86WoeYMVxgI690HbepnGO6VUtloNWB5p3/iEjMkAwzGPRI/6YJK2nSghfZj0ylMTlOO0NbRsEZs/Lmr5SQVy4fZS+OZP7qYfBxFQinCxplQx8MK8pDnrVM2p2m7XSk6jb7cAEmzbGBH5cUMAdy67en7acJOlAzGwj5dGO9POC0J74PMLSPocOxAjYq6wLvLPRvg/FcWzNdkw/2hXzI/KFAmBOCdNAyQqQeMtrMoZCPpN6DQDmOjdyPEMlksTlKXSsgbUmHMcsSdh5d3DtFnzla3WlHOZWR97lmA2y02B7SLGrLrXjqam1xJWG+J4lbLrXlCiYAOZnDYBTww/WlYQ3oP6drgqwxAYdUOlUomc20NkZJy3WujZUGlWAk5YMc10rF0HKcfy25HqnIcvP0lSUx1fw2Kqs9HVWNXreJRiokBbnVCgg1OfYbdovM8vXC/BRYQ=
    on:
      tags: true
      all_branches: true # needed due to travis limitation, we deploy only on master
